### PR TITLE
Add some missing 3.8 methods to typing stubs

### PR DESCRIPTION
**Pull request by taralx**
Copied from typeshed.

### CODE REVIEW

**Comment by taralx** [comment]
Added to Amazon Corporate CLA.

**Comment by taralx** [comment]
@googlebot I signed it!

**Comment by taralx** [comment]
Ping.

**Comment by taralx** [comment]
Updated to use `Optional` in case that matters to some older versions.

**Comment by rchen152** [comment]
Thanks for the PR, and sorry for the delay! (I just got back from vacation.) Looks good to me; let's see what the tests say.

**Review by rchen152 — APPROVED** [review]

**Comment by rchen152** [comment]
Alright, looks like the tests passed. I'll go ahead and import this PR for internal review; since Monday is a U.S. holiday, it'll probably be merged sometime on Tuesday.

**Pull request closed without merging**
