### PR TITLE
Updating Setup.cfg

### PR DESCRIPTION
**Pull request by priyansh19**
Adding comments in Setup.cfg file

### CODE REVIEW

**Comment by rchen152** [comment]
Hi Priyansh! Thank you for the PR. Could you explain what the purpose of adding these comments is? This setup.cfg file isn't the template that pytype uses to generate configurations; it's pytype's own configuration to type-check itself.

**Comment by priyansh19** [comment]
I thought, it was needed so as to help beginners to understand the basic requirements and libraries that will be used in Pytpe.

**Comment by KevinHock** [comment]
IMO This is a slippery slope, where one could add comments to anything for beginners, e.g.

# iterate through thing
For t in thing:

So this feels somewhat unnecessary.

**Comment by rchen152** [comment]
Sorry for letting this sit for so long. Now that I'm revisiting it, I agree with @KevinHock - these comments don't appear to add much value. I'm going to close this PR, but @priyansh19, thank you for your time on it.

**Pull request closed without merging**
