### PR TITLE
Add ImportError attributes name, path for Python 3.3+

### LINKED ISSUE #769: ImportError name and path attributes not known
```shellsession
$ pytype --version
2020.12.16
$ cat t.py 
try:
    import nonexistent
except ImportError as err:
    print(err.name)
    print(err.path)
$ pytype t.py | grep ^File
File "/tmp/t.py", line 2, in <module>: Can't find module 'nonexistent'. [import-error]
File "/tmp/t.py", line 4, in <module>: No attribute 'name' on ImportError [attribute-error]
File "/tmp/t.py", line 5, in <module>: No attribute 'path' on ImportError [attribute-error]
```

The `name` and `path` attributes were added in 3.3, typeshed has them.
https://docs.python.org/3.9/library/exceptions.html#ImportError

### PR DESCRIPTION
**Pull request by parampatidar**
Fixes #769

### CODE REVIEW

**Comment by parampatidar** [comment]
@googlebot I signed it!

**Comment by martindemello** [comment]
thanks! could you also add a test to this file: https://github.com/google/pytype/blob/master/pytype/tests/test_import.py

you can use the [CheckWithErrors](https://github.com/google/pytype/blob/master/pytype/tests/test_import.py#L1133) test method on the code from #769, checking that only the `import-error` is present - something like:
```
self.CheckWithErrors("""
   try:
     import nonexistent  # import-error
   except ImportError as e:
     print(e.name)
""")
```
which will fail if the `attribute-error` is still raised.

**Comment by parampatidar** [comment]
@martindemello Thanks! for guiding me but I'm unable to run tests. I found out that I'm getting same error as #405 describes. Though I'm using WSL2.

**Comment by parampatidar** [comment]
I'm checking with below code as according to [typeshed](https://github.com/python/typeshed/blob/4f81ac10aec63e0e0672647f2369b4ee42d35f62/stdlib/3/builtins.pyi#L1300).

```python
class ImportError(StandardError):
    def __init__(self, *args: object, name: Optional[str] = ..., path: Optional[str] = ...) -> None: ...
    name: Optional[str]
    path: Optional[str]
```

and test code :
```python
def test_import_attribute_error(self):
    with file_utils.Tempdir() as d:
      self.CheckWithErrors("""
        try:
          import nonexistent
        except ImportError as err:
          print(err.name)
      """, pythonpath=[d.path])
```
but getting following in `build.log`

```
[1/2] Generating test_import.py
[2/2] Generating test_import.log
FAILED: pytype/tests/test_import.log
cd /home/param/opensource/google/pytype/out/pytype/tests && TYPESHED_HOME=/home/param/opensource/google/pytype/typeshed /home/param/miniconda3/envs/ospytype/bin/python3.8 -B /home/param/opensource/google/pytype/build_scripts/test_module.py pytype.tests.test_import -o /home/param/opensource/google/pytype/out/pytype/tests/test_import.log -P /home/param/opensource/google/pytype/out -s -p
WARNING:pytype.attribute:Ignoring overwrite of sys.path
WARNING:pytype.load_pytd:Couldn't import module a.bar 'a.bar' in (path=['/tmp/tmp1z6th__d']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'a.bar'
WARNING:pytype.load_pytd:Couldn't import module a.baz 'a.baz' in (path=['/tmp/tmp1z6th__d']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'a.baz'
WARNING:pytype.load_pytd:Couldn't import module nonsense 'nonsense' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonsense'
WARNING:pytype.load_pytd:Couldn't import module other_nonsense 'other_nonsense' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'other_nonsense'
WARNING:pytype.load_pytd:Couldn't import module bad_import 'bad_import' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'bad_import'
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'path.to.module'
WARNING:pytype.load_pytd:Couldn't import module module 'module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'module'
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'path.to.module'
WARNING:pytype.load_pytd:Couldn't import module nonexistent 'nonexistent' in (path=['/tmp/tmpvkwfm3q7']) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonexistent'
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/__init__'
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/tmpd78qw9tp/__init__'
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/tmpd78qw9tp/foo/__init__'
WARNING:pytype.load_pytd:Couldn't import module package.submodule 'package.submodule' in (path=['/tmp/tmpbolbbz11']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'package.submodule'
WARNING:pytype.load_pytd:Couldn't import module nonexistant_path 'nonexistant_path' in (path=['/tmp/tmpimu07pgx']) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonexistant_path'
WARNING:pytype.load_pytd:Couldn't import module unknown_module 'unknown_module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'unknown_module'
WARNING:pytype.load_pytd:Couldn't import module package.submodule.asd 'package.submodule.asd' in (path=['/tmp/tmp1ik83t5p']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'package.submodule.asd'
WARNING:pytype.abstract:Couldn't find attribute / module 'sub.bar.quux'
WARNING:pytype.attribute:Ignoring overwrite of sys.path
WARNING:pytype.load_pytd:Couldn't import module a.bar 'a.bar' in (path=['/tmp/tmp4hfknqa7']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'a.bar'
WARNING:pytype.load_pytd:Couldn't import module a.baz 'a.baz' in (path=['/tmp/tmp4hfknqa7']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'a.baz'
WARNING:pytype.load_pytd:Couldn't import module nonsense 'nonsense' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module nonsense 'nonsense' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonsense'
WARNING:pytype.load_pytd:Couldn't import module other_nonsense 'other_nonsense' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module other_nonsense 'other_nonsense' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'other_nonsense'
WARNING:pytype.load_pytd:Couldn't import module bad_import 'bad_import' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'bad_import'
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'path.to.module'
WARNING:pytype.load_pytd:Couldn't import module module 'module' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module module 'module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'module'
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module path.to.module 'path.to.module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'path.to.module'
WARNING:pytype.load_pytd:Couldn't import module nonexistent 'nonexistent' in (path=['/tmp/tmpn6_5lof1']) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module nonexistent 'nonexistent' in (path=['/tmp/tmpn6_5lof1']) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonexistent'

Running tests in module pytype.tests.test_import ...

Running test methods in class pytype.tests.test_import.ImportTest ...
PASS: pytype.tests.test_import.ImportTest.test_assign_member
PASS: pytype.tests.test_import.ImportTest.test_attr_and_module
PASS: pytype.tests.test_import.ImportTest.test_attribute_on_module
PASS: pytype.tests.test_import.ImportTest.test_bad_star_import
PASS: pytype.tests.test_import.ImportTest.test_basic_import
PASS: pytype.tests.test_import.ImportTest.test_basic_import2
PASS: pytype.tests.test_import.ImportTest.test_circular
PASS: pytype.tests.test_import.ImportTest.test_class_alias
PASS: pytype.tests.test_import.ImportTest.test_deep_dependency
PASS: pytype.tests.test_import.ImportTest.test_dot_dot
PASS: pytype.tests.test_import.ImportTest.test_dot_dot_in_pyi
PASS: pytype.tests.test_import.ImportTest.test_dot_dot_packag_no_init
PASS: pytype.tests.test_import.ImportTest.test_dot_dot_package
PASS: pytype.tests.test_import.ImportTest.test_dot_dot_package_in_pyi
PASS: pytype.tests.test_import.ImportTest.test_dot_package
PASS: pytype.tests.test_import.ImportTest.test_dot_package_no_init
PASS: pytype.tests.test_import.ImportTest.test_file_import1
PASS: pytype.tests.test_import.ImportTest.test_file_import2
PASS: pytype.tests.test_import.ImportTest.test_from_dot_in_pyi
PASS: pytype.tests.test_import.ImportTest.test_from_import
PASS: pytype.tests.test_import.ImportTest.test_from_import_smoke
PASS: pytype.tests.test_import.ImportTest.test_from_sys_import
PASS: pytype.tests.test_import.ImportTest.test_get_bad_submodule_as_attribute
PASS: pytype.tests.test_import.ImportTest.test_ignored_import
PASS: pytype.tests.test_import.ImportTest.test_import_alias
PASS: pytype.tests.test_import.ImportTest.test_import_all
FAIL: pytype.tests.test_import.ImportTest.test_import_attribute_error
Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 227, in assert_errors_match_expected
    line, code, mark = next(expected_errors)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_import.py", line 1140, in test_import_attribute_error
    self.CheckWithErrors("""
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_base.py", line 231, in CheckWithErrors
    errorlog.assert_errors_match_expected()
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 229, in assert_errors_match_expected
    self._fail("Unexpected error:\n%s" % error)
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 209, in _fail
    raise AssertionError(msg)
AssertionError: Unexpected error:
File "<inline>", line 2, in <module>: Can't find module 'nonexistent'. [import-error]

PASS: pytype.tests.test_import.ImportTest.test_import_builtins
PASS: pytype.tests.test_import.ImportTest.test_import_constant
PASS: pytype.tests.test_import.ImportTest.test_import_directory
PASS: pytype.tests.test_import.ImportTest.test_import_function
PASS: pytype.tests.test_import.ImportTest.test_import_init
PASS: pytype.tests.test_import.ImportTest.test_import_map
PASS: pytype.tests.test_import.ImportTest.test_import_map_filter
PASS: pytype.tests.test_import.ImportTest.test_import_name
PASS: pytype.tests.test_import.ImportTest.test_import_package_alias_name_conflict
PASS: pytype.tests.test_import.ImportTest.test_import_package_alias_name_conflict2
PASS: pytype.tests.test_import.ImportTest.test_import_package_alias_name_conflict3
PASS: pytype.tests.test_import.ImportTest.test_import_package_as_alias
PASS: pytype.tests.test_import.ImportTest.test_import_pytd
PASS: pytype.tests.test_import.ImportTest.test_import_pytd2
PASS: pytype.tests.test_import.ImportTest.test_import_resolve_on_dummy
PASS: pytype.tests.test_import.ImportTest.test_import_type_factory
PASS: pytype.tests.test_import.ImportTest.test_imported_constants
PASS: pytype.tests.test_import.ImportTest.test_imported_method_as_class_attribute
PASS: pytype.tests.test_import.ImportTest.test_init_only_submodule
PASS: pytype.tests.test_import.ImportTest.test_long_from
PASS: pytype.tests.test_import.ImportTest.test_match_against_imported
PASS: pytype.tests.test_import.ImportTest.test_match_module
PASS: pytype.tests.test_import.ImportTest.test_module_class_conflict
PASS: pytype.tests.test_import.ImportTest.test_module_reexports_and_aliases
PASS: pytype.tests.test_import.ImportTest.test_mutual_imports
PASS: pytype.tests.test_import.ImportTest.test_no_fail_on_bad_symbol_lookup
PASS: pytype.tests.test_import.ImportTest.test_path_import
PASS: pytype.tests.test_import.ImportTest.test_path_import2
PASS: pytype.tests.test_import.ImportTest.test_redefined_builtin
PASS: pytype.tests.test_import.ImportTest.test_redefined_builtin2
PASS: pytype.tests.test_import.ImportTest.test_reimport
PASS: pytype.tests.test_import.ImportTest.test_relative_import
PASS: pytype.tests.test_import.ImportTest.test_relative_star_import
PASS: pytype.tests.test_import.ImportTest.test_relative_star_import2
PASS: pytype.tests.test_import.ImportTest.test_return_module
PASS: pytype.tests.test_import.ImportTest.test_solve_for_imported
PASS: pytype.tests.test_import.ImportTest.test_star_import
PASS: pytype.tests.test_import.ImportTest.test_star_import_any
PASS: pytype.tests.test_import.ImportTest.test_star_import_in_pyi
PASS: pytype.tests.test_import.ImportTest.test_star_import_smoke
PASS: pytype.tests.test_import.ImportTest.test_star_import_unknown_smoke
PASS: pytype.tests.test_import.ImportTest.test_stdlib
PASS: pytype.tests.test_import.ImportTest.test_subdir_and_module_with_same_name_as_package
PASS: pytype.tests.test_import.ImportTest.test_submodule_attribute_error
PASS: pytype.tests.test_import.ImportTest.test_subpackage
PASS: pytype.tests.test_import.ImportTest.test_sys
PASS: pytype.tests.test_import.ImportTest.test_too_many_dots_in_package_in_pyi
PASS: pytype.tests.test_import.ImportTest.test_two_level
PASS: pytype.tests.test_import.ImportTest.test_unimported_submodule_failure
PASS: pytype.tests.test_import.ImportTest.test_unused_from_dot_in_pyi

Running test methods in class pytype.tests.test_import.ImportTestPy2 ...
PASS: pytype.tests.test_import.ImportTestPy2.test_assign_member
PASS: pytype.tests.test_import.ImportTestPy2.test_attr_and_module
PASS: pytype.tests.test_import.ImportTestPy2.test_attribute_on_module
PASS: pytype.tests.test_import.ImportTestPy2.test_bad_star_import
PASS: pytype.tests.test_import.ImportTestPy2.test_basic_import
PASS: pytype.tests.test_import.ImportTestPy2.test_basic_import2
PASS: pytype.tests.test_import.ImportTestPy2.test_circular
PASS: pytype.tests.test_import.ImportTestPy2.test_class_alias
PASS: pytype.tests.test_import.ImportTestPy2.test_deep_dependency
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_dot
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_dot_in_pyi
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_dot_packag_no_init
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_dot_package
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_dot_package_in_pyi
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_package
PASS: pytype.tests.test_import.ImportTestPy2.test_dot_package_no_init
PASS: pytype.tests.test_import.ImportTestPy2.test_file_import1
PASS: pytype.tests.test_import.ImportTestPy2.test_file_import2
PASS: pytype.tests.test_import.ImportTestPy2.test_from_dot_in_pyi
PASS: pytype.tests.test_import.ImportTestPy2.test_from_import
PASS: pytype.tests.test_import.ImportTestPy2.test_from_import_smoke
PASS: pytype.tests.test_import.ImportTestPy2.test_from_sys_import
PASS: pytype.tests.test_import.ImportTestPy2.test_get_bad_submodule_as_attribute
PASS: pytype.tests.test_import.ImportTestPy2.test_ignored_import
PASS: pytype.tests.test_import.ImportTestPy2.test_import_alias
PASS: pytype.tests.test_import.ImportTestPy2.test_import_all
FAIL: pytype.tests.test_import.ImportTestPy2.test_import_attribute_error
Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 227, in assert_errors_match_expected
    line, code, mark = next(expected_errors)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_import.py", line 1140, in test_import_attribute_error
    self.CheckWithErrors("""
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_base.py", line 231, in CheckWithErrors
    errorlog.assert_errors_match_expected()
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 229, in assert_errors_match_expected
    self._fail("Unexpected error:\n%s" % error)
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 209, in _fail
    raise AssertionError(msg)
AssertionError: Unexpected error:
File "<inline>", line 2, in <module>: Can't find module 'nonexistent'. [import-error]
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/__init__'
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/tmp1eui52ir/__init__'
WARNING:pytype.imports_map_loader:Created empty __init__ 'tmp/tmp1eui52ir/foo/__init__'
WARNING:pytype.load_pytd:Couldn't import module package.submodule 'package.submodule' in (path=['/tmp/tmpmcedz7ux']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'package.submodule'
WARNING:pytype.load_pytd:Couldn't import module nonexistant_path 'nonexistant_path' in (path=['/tmp/tmpd0p9n98o']) imports_map: none
WARNING:pytype.vm:Couldn't find module 'nonexistant_path'
WARNING:pytype.load_pytd:Couldn't import module unknown_module 'unknown_module' in (path=()) imports_map: none
WARNING:pytype.load_pytd:Couldn't import module unknown_module 'unknown_module' in (path=()) imports_map: none
WARNING:pytype.vm:Couldn't find module 'unknown_module'
WARNING:pytype.load_pytd:Couldn't import module package.submodule.asd 'package.submodule.asd' in (path=['/tmp/tmpgi34ik3k']) imports_map: none
WARNING:pytype.abstract:Couldn't find attribute / module 'package.submodule.asd'
WARNING:pytype.abstract:Couldn't find attribute / module 'sub.bar.quux'

PASS: pytype.tests.test_import.ImportTestPy2.test_import_builtins
PASS: pytype.tests.test_import.ImportTestPy2.test_import_constant
PASS: pytype.tests.test_import.ImportTestPy2.test_import_directory
PASS: pytype.tests.test_import.ImportTestPy2.test_import_function
PASS: pytype.tests.test_import.ImportTestPy2.test_import_init
PASS: pytype.tests.test_import.ImportTestPy2.test_import_map
PASS: pytype.tests.test_import.ImportTestPy2.test_import_map_filter
PASS: pytype.tests.test_import.ImportTestPy2.test_import_name
PASS: pytype.tests.test_import.ImportTestPy2.test_import_package_alias_name_conflict
PASS: pytype.tests.test_import.ImportTestPy2.test_import_package_alias_name_conflict2
PASS: pytype.tests.test_import.ImportTestPy2.test_import_package_alias_name_conflict3
PASS: pytype.tests.test_import.ImportTestPy2.test_import_package_as_alias
PASS: pytype.tests.test_import.ImportTestPy2.test_import_pytd
PASS: pytype.tests.test_import.ImportTestPy2.test_import_pytd2
PASS: pytype.tests.test_import.ImportTestPy2.test_import_resolve_on_dummy
PASS: pytype.tests.test_import.ImportTestPy2.test_import_type_factory
PASS: pytype.tests.test_import.ImportTestPy2.test_imported_constants
PASS: pytype.tests.test_import.ImportTestPy2.test_imported_method_as_class_attribute
PASS: pytype.tests.test_import.ImportTestPy2.test_init_only_submodule
PASS: pytype.tests.test_import.ImportTestPy2.test_long_from
PASS: pytype.tests.test_import.ImportTestPy2.test_match_against_imported
PASS: pytype.tests.test_import.ImportTestPy2.test_match_module
PASS: pytype.tests.test_import.ImportTestPy2.test_module_class_conflict
PASS: pytype.tests.test_import.ImportTestPy2.test_module_reexports_and_aliases
PASS: pytype.tests.test_import.ImportTestPy2.test_mutual_imports
PASS: pytype.tests.test_import.ImportTestPy2.test_no_fail_on_bad_symbol_lookup
PASS: pytype.tests.test_import.ImportTestPy2.test_path_import
PASS: pytype.tests.test_import.ImportTestPy2.test_path_import2
PASS: pytype.tests.test_import.ImportTestPy2.test_redefined_builtin
PASS: pytype.tests.test_import.ImportTestPy2.test_redefined_builtin2
PASS: pytype.tests.test_import.ImportTestPy2.test_reimport
PASS: pytype.tests.test_import.ImportTestPy2.test_relative_import
PASS: pytype.tests.test_import.ImportTestPy2.test_relative_star_import
PASS: pytype.tests.test_import.ImportTestPy2.test_relative_star_import2
PASS: pytype.tests.test_import.ImportTestPy2.test_return_module
PASS: pytype.tests.test_import.ImportTestPy2.test_solve_for_imported
PASS: pytype.tests.test_import.ImportTestPy2.test_star_import
PASS: pytype.tests.test_import.ImportTestPy2.test_star_import_any
PASS: pytype.tests.test_import.ImportTestPy2.test_star_import_in_pyi
PASS: pytype.tests.test_import.ImportTestPy2.test_star_import_smoke
PASS: pytype.tests.test_import.ImportTestPy2.test_star_import_unknown_smoke
PASS: pytype.tests.test_import.ImportTestPy2.test_stdlib
PASS: pytype.tests.test_import.ImportTestPy2.test_subdir_and_module_with_same_name_as_package
PASS: pytype.tests.test_import.ImportTestPy2.test_submodule_attribute_error
PASS: pytype.tests.test_import.ImportTestPy2.test_subpackage
PASS: pytype.tests.test_import.ImportTestPy2.test_sys
PASS: pytype.tests.test_import.ImportTestPy2.test_too_many_dots_in_package_in_pyi
PASS: pytype.tests.test_import.ImportTestPy2.test_two_level
PASS: pytype.tests.test_import.ImportTestPy2.test_unimported_submodule_failure
PASS: pytype.tests.test_import.ImportTestPy2.test_unused_from_dot_in_pyi

Ran 154 methods from 2 classes.
Found 0 errors
Found 2 failures
Found 0 unexpected successes

>>> FAIL - pytype.tests.test_import - /home/param/opensource/google/pytype/out/pytype/tests/test_import.log
ninja: build stopped: cannot make progress due to previous errors.

>>> Found Ninja target failures (includes test failures):
    - pytype/tests/test_import.log
```

**Comment by martindemello** [comment]
the test is slightly wrong - it should be
```
def test_import_attribute_error(self):
    self.CheckWithErrors("""
      try:
        import nonexistent  # import-error
      except ImportError as err:
        print(err.name)
    """)
```

you don't need the tempdir in this case because it's for tests that involve multiple files and we only have a single one here, and you do need to add the `# import-error` comment because that tells `CheckWithErrors` what errors to anticipate.

**Comment by martindemello** [comment]
we've not been able to figure out #405 unfortunately, since all of us use linux :( but we will import the PR into our internal repo, test it and reexport to github (you'll still be credited as the author)

**Comment by parampatidar** [comment]
I have test tested with the code as you mentioned that I do need `# import-error`  but still getting failure on test.
```
FAIL: pytype.tests.test_import.ImportTestPy2.test_import_attribute_error
Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 227, in assert_errors_match_expected
    line, code, mark = next(expected_errors)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_import.py", line 1139, in test_import_attribute_error
    self.CheckWithErrors("""
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_base.py", line 231, in CheckWithErrors
    errorlog.assert_errors_match_expected()
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 229, in assert_errors_match_expected
    self._fail("Unexpected error:\n%s" % error)
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 209, in _fail
    raise AssertionError(msg)
AssertionError: Unexpected error:
File "<inline>", line 4, in <module>: No attribute 'name' on ImportError [attribute-error]
```

But if I specify `attribute-error` as following :
```python
  def test_import_attribute_error(self):
      self.CheckWithErrors("""
        try:
          import nonexistent  # import-error
        except ImportError as err:
          print(err.name)  # attribute-error
      """)
```
then test should be passed but log file says `Errors Not Found` as following : 
```
FAIL: pytype.tests.test_import.ImportTest.test_import_attribute_error
Traceback (most recent call last):
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_import.py", line 1139, in test_import_attribute_error
    self.CheckWithErrors("""
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_base.py", line 231, in CheckWithErrors
    errorlog.assert_errors_match_expected()
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 238, in assert_errors_match_expected
    self._fail("Errors not found:\n" + "\n".join(leftover_errors))
  File "/home/param/opensource/google/pytype/out/pytype/tests/test_utils.py", line 209, in _fail
    raise AssertionError(msg)
AssertionError: Errors not found:
Line 4: attribute-error
```

**Comment by rchen152** [comment]
It looks like your tests are in tests/test_import.py. The tests directly under the tests/ directory are run in both Python 2 and Python 3 (see https://github.com/google/pytype/blob/master/pytype/tests/README.md). Since the name and path attributes exist only in Python 3, try putting your tests in tests/py3/test_import.py instead.

**Comment by martindemello** [comment]
looks good, thanks! following our workflow, i'll close the pull request and merge this commit internally, and we'll push it out with our next pytype release (which should be shortly after new year's day)

**Pull request closed without merging**
