### PR TITLE
Google sync

### PR DESCRIPTION
**Pull request by rchen152**

### CODE REVIEW

**Comment by rchen152** [comment]
Huh, test failures. I'll look into it.

**Comment by rchen152** [comment]
The failures appear to start at https://github.com/google/pytype/commit/c984adadbe5e86be4ca1ef46671cf93239a459c8. I copied a terminal transcript at the bottom of this comment. It looks like an innocuous change; any idea what the issue might be?

```
$ python build_scripts/run_tests.py 
Running with the cached Python version; not cleaning 'out' directory.

Running CMake skipped ...

Running tests (build steps will be executed as required) ...

>>> PASS - pytype.imports_map_loader_test

>>> PASS - pytype.file_utils_test

>>> PASS - pytype.datatypes_test

>>> PASS - pytype.utils_test

>>> PASS - pytype.module_utils_test

>>> PASS - pytype.state_test

>>> PASS - pytype.directors_test

>>> PASS - pytype.collections_overlay_test

>>> PASS - pytype.blocks_test

>>> PASS - pytype.config_test

>>> PASS - pytype.convert_structural_test

>>> PASS - pytype.attribute_test

>>> PASS - pytype.vm_test

>>> PASS - pytype.tests.test_protocols

>>> PASS - pytype.tests.test_unions

>>> PASS - pytype.pytd.serialize_ast_test

>>> PASS - pytype.tests.test_slice

>>> PASS - pytype.load_pytd_test

>>> PASS - pytype.tests.test_disables

>>> PASS - pytype.tests.test_compile_to_pyc

>>> PASS - pytype.tests.test_quick

>>> PASS - pytype.tests.test_operators2

>>> PASS - pytype.tests.test_dict

>>> PASS - pytype.tests.test_options

>>> PASS - pytype.tests.test_inheritance

>>> PASS - pytype.tests.test_anystr

>>> PASS - pytype.convert_test

>>> PASS - pytype.tests.test_abc

>>> PASS - pytype.tests.test_tuple

>>> PASS - pytype.tests.test_match

>>> PASS - pytype.tests.test_logic

>>> PASS - pytype.tests.test_generators

>>> PASS - pytype.tests.test_recovery

>>> PASS - pytype.tests.py2.test_typing_namedtuple

>>> PASS - pytype.tests.py2.test_flow

>>> PASS - pytype.tests.test_calls

>>> PASS - pytype.tests.py2.test_protocol_inference

>>> PASS - pytype.tests.py2.test_tuple

>>> PASS - pytype.tests.py2.test_match

>>> PASS - pytype.tests.py2.test_slice

>>> PASS - pytype.tests.test_special_builtins

>>> PASS - pytype.tests.py2.test_stdlib

>>> PASS - pytype.tests.test_typing_namedtuple

>>> PASS - pytype.tests.py2.test_operators

>>> PASS - pytype.matcher_test

>>> PASS - pytype.tests.test_tracebacks

>>> PASS - pytype.tests.test_typing

>>> PASS - pytype.tests.test_six_overlay

>>> PASS - pytype.tests.py2.test_typing_methods

>>> PASS - pytype.tests.py2.test_errors

>>> PASS - pytype.tests.test_closures

>>> PASS - pytype.tests.py2.test_functions

>>> PASS - pytype.tests.test_with

>>> PASS - pytype.tests.py2.test_decorators

>>> PASS - pytype.tests.py2.test_exceptions

>>> PASS - pytype.tests.py2.test_recovery

>>> PASS - pytype.tests.py2.test_import

>>> PASS - pytype.tests.test_list

>>> PASS - pytype.tests.test_pickle

>>> PASS - pytype.tests.py2.test_list

>>> PASS - pytype.tests.py2.test_super

>>> PASS - pytype.tests.py2.test_slots

>>> PASS - pytype.tests.py2.test_anystr

>>> PASS - pytype.tests.py2.test_basic

>>> PASS - pytype.tests.test_slots

>>> PASS - pytype.tests.py2.test_methods

>>> PASS - pytype.tests.py2.test_typevar

>>> PASS - pytype.tests.py2.test_six_overlay

>>> PASS - pytype.tests.py2.test_namedtuple

>>> PASS - pytype.tests.py2.test_pyi

>>> PASS - pytype.tests.py2.test_attributes

>>> PASS - pytype.tests.test_decorators

>>> PASS - pytype.tests.py2.test_typing

>>> PASS - pytype.tests.py2.test_inplace

>>> PASS - pytype.tests.py3.test_pyi

>>> PASS - pytype.tests.py3.test_recovery

>>> PASS - pytype.tests.py3.test_namedtuple

>>> PASS - pytype.tests.test_exceptions

>>> PASS - pytype.tests.py2.test_abc

>>> PASS - pytype.tests.py3.test_abc

>>> PASS - pytype.tests.py3.test_slots

>>> PASS - pytype.tests.py2.test_containers

>>> PASS - pytype.tests.py3.test_flow

>>> PASS - pytype.tests.test_super

>>> PASS - pytype.tests.py3.test_list

>>> PASS - pytype.tests.py3.test_dict

>>> PASS - pytype.tests.py3.test_type_comments

>>> PASS - pytype.tests.py3.test_pickle

>>> PASS - pytype.tests.test_solver

>>> PASS - pytype.tests.py3.test_methods

>>> PASS - pytype.tests.py3.test_inplace

>>> PASS - pytype.tests.py3.test_typing_namedtuple

>>> PASS - pytype.tests.py3.test_decorators

>>> PASS - pytype.tests.test_builtins3

>>> PASS - pytype.tests.test_cmp

>>> PASS - pytype.tests.py3.test_exceptions

>>> PASS - pytype.tests.py3.test_anystr

>>> PASS - pytype.tools.analyze_project.config_test

>>> PASS - pytype.tests.py3.test_slice

>>> PASS - pytype.tests.py2.test_builtins

>>> PASS - pytype.tools.analyze_project.parse_args_test

>>> PASS - pytype.tests.py3.test_generators

>>> PASS - pytype.tests.py3.test_reingest

>>> PASS - pytype.tools.analyze_project.pytype_runner_test

>>> PASS - pytype.tests.test_typing_methods

>>> PASS - pytype.tests.py3.test_cmp

>>> PASS - pytype.tests.py3.test_import

>>> PASS - pytype.tests.py3.test_special_builtins

>>> PASS - pytype.tests.py3.test_six_overlay

>>> PASS - pytype.tests.py3.test_basic

>>> PASS - pytype.tests.py3.test_operators

>>> PASS - pytype.tests.py3.test_typing_methods

>>> PASS - pytype.tests.py3.test_attributes

>>> PASS - pytype.tests.py3.test_checker

>>> PASS - pytype.tests.test_typevar

>>> PASS - pytype.tests.py3.test_errors

>>> PASS - pytype.tests.test_flow

>>> PASS - pytype.tests.py3.test_super

>>> PASS - pytype.tests.py3.test_tuple

>>> PASS - pytype.tests.py3.test_match

>>> PASS - pytype.tests.py3.test_classes

>>> PASS - pytype.tests.test_namedtuple

>>> PASS - pytype.tests.test_stdlib

>>> PASS - pytype.tests.py3.test_functions

>>> PASS - pytype.tests.py3.test_splits

>>> PASS - pytype.tests.test_reingest

>>> PASS - pytype.abstract_test

>>> PASS - pytype.tests.test_pyi

>>> PASS - pytype.tests.py3.test_protocols

>>> PASS - pytype.tests.test_inplace

>>> PASS - pytype.tests.test_splits

>>> PASS - pytype.tests.py3.test_typing

>>> PASS - pytype.tests.py3.test_typevar

>>> PASS - pytype.tests.test_generic

>>> PASS - pytype.tests.py3.test_builtins

>>> PASS - pytype.tests.test_builtins1

>>> PASS - pytype.tests.py3.test_stdlib

>>> PASS - pytype.tests.test_attributes

>>> PASS - pytype.tests.test_builtins2

>>> PASS - pytype.tests.test_type_comments

>>> PASS - pytype.tests.test_basic

>>> PASS - pytype.tests.py3.test_annotations

>>> PASS - pytype.tests.test_import

>>> PASS - pytype.tests.test_functions

>>> PASS - pytype.tests.test_protocol_inference

>>> PASS - pytype.tests.test_classes

>>> PASS - pytype.tests.test_operators

>>> PASS - pytype.tests.test_errors

Failure while running command: ['ninja', '-k', '100000', 'test_all'].
Run it in the 'out' directory for more information.
$ cd out/
$ ninja -k 100000 test_all
[1/2] Generating test_containers.log
FAILED: pytype/tests/test_containers.log 
cd /usr/local/google/home/rechen/pytype/out/pytype/tests && TYPESHED_HOME=/usr/local/google/home/rechen/pytype/typeshed /usr/bin/python2.7 -B /usr/local/google/home/rechen/pytype/build_scripts/test_module.py pytype.tests.test_containers -o /usr/local/google/home/rechen/pytype/out/pytype/tests/test_containers.log -P /usr/local/google/home/rechen/pytype/out -S
[2/2] Generating test_methods.log
FAILED: pytype/tests/test_methods.log 
cd /usr/local/google/home/rechen/pytype/out/pytype/tests && TYPESHED_HOME=/usr/local/google/home/rechen/pytype/typeshed /usr/bin/python2.7 -B /usr/local/google/home/rechen/pytype/build_scripts/test_module.py pytype.tests.test_methods -o /usr/local/google/home/rechen/pytype/out/pytype/tests/test_methods.log -P /usr/local/google/home/rechen/pytype/out -S
ninja: build stopped: cannot make progress due to previous errors.
$ cat pytype/tests/test_containers.log 
$ cat pytype/tests/test_methods.log 

Running tests in module pytype.tests.test_methods ...

Running test methods in class pytype.tests.test_methods.MethodsTest ...
PASS: pytype.tests.test_methods.MethodsTest.testClassMethodSmoke_py2
PASS: pytype.tests.test_methods.MethodsTest.testClassMethodSmoke_py3
PASS: pytype.tests.test_methods.MethodsTest.testMultipleReturns_py2
PASS: pytype.tests.test_methods.MethodsTest.testMultipleReturns_py3
PASS: pytype.tests.test_methods.MethodsTest.testIsNot_py2
PASS: pytype.tests.test_methods.MethodsTest.testIsNot_py3
PASS: pytype.tests.test_methods.MethodsTest.testBuiltinStarStarArgs_py3
PASS: pytype.tests.test_methods.MethodsTest.testBuiltinStarStarArgs_py2
PASS: pytype.tests.test_methods.MethodsTest.testInNotIn_py2
PASS: pytype.tests.test_methods.MethodsTest.testInNotIn_py3
PASS: pytype.tests.test_methods.MethodsTest.testFlowAndReplacementSanity_py3
PASS: pytype.tests.test_methods.MethodsTest.testFlowAndReplacementSanity_py2
PASS: pytype.tests.test_methods.MethodsTest.testCallKwArgs_py3
PASS: pytype.tests.test_methods.MethodsTest.testCallKwArgs_py2
PASS: pytype.tests.test_methods.MethodsTest.testBuiltinKeyword_py2
PASS: pytype.tests.test_methods.MethodsTest.testBuiltinKeyword_py3
PASS: pytype.tests.test_methods.MethodsTest.testTwoDistinctKeywordParams_py3
PASS: pytype.tests.test_methods.MethodsTest.testTwoDistinctKeywordParams_py2
PASS: pytype.tests.test_methods.MethodsTest.testRecursion_py3
PASS: pytype.tests.test_methods.MethodsTest.testRecursion_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarStarDeep_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarStarDeep_py3
PASS: pytype.tests.test_methods.MethodsTest.testIs_py2
PASS: pytype.tests.test_methods.MethodsTest.testIs_py3
PASS: pytype.tests.test_methods.MethodsTest.testCopyMethod_py2
PASS: pytype.tests.test_methods.MethodsTest.testCopyMethod_py3
PASS: pytype.tests.test_methods.MethodsTest.testSimpleStaticMethod_py3
PASS: pytype.tests.test_methods.MethodsTest.testSimpleStaticMethod_py2
PASS: pytype.tests.test_methods.MethodsTest.testJson_py2
PASS: pytype.tests.test_methods.MethodsTest.testJson_py3
PASS: pytype.tests.test_methods.MethodsTest.testConvert_py2
PASS: pytype.tests.test_methods.MethodsTest.testConvert_py3
PASS: pytype.tests.test_methods.MethodsTest.testUnknownDecorator_py3
PASS: pytype.tests.test_methods.MethodsTest.testUnknownDecorator_py2
PASS: pytype.tests.test_methods.MethodsTest.testBranchAndLoopCFG_py3
PASS: pytype.tests.test_methods.MethodsTest.testBranchAndLoopCFG_py2
PASS: pytype.tests.test_methods.MethodsTest.testFunctionAttr_py3
PASS: pytype.tests.test_methods.MethodsTest.testFunctionAttr_py2
PASS: pytype.tests.test_methods.MethodsTest.testCallArgsKwArgs_py2
PASS: pytype.tests.test_methods.MethodsTest.testCallArgsKwArgs_py3
PASS: pytype.tests.test_methods.MethodsTest.testClassSanity_py3
PASS: pytype.tests.test_methods.MethodsTest.testClassSanity_py2
PASS: pytype.tests.test_methods.MethodsTest.testOverrideNew_py3
PASS: pytype.tests.test_methods.MethodsTest.testOverrideNew_py2
PASS: pytype.tests.test_methods.MethodsTest.testClosureBindingArguments_py3
PASS: pytype.tests.test_methods.MethodsTest.testClosureBindingArguments_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarStarKwargsType_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarStarKwargsType_py2
PASS: pytype.tests.test_methods.MethodsTest.testInheritance_py3
PASS: pytype.tests.test_methods.MethodsTest.testInheritance_py2
PASS: pytype.tests.test_methods.MethodsTest.testInheritedClassMethod_py3
PASS: pytype.tests.test_methods.MethodsTest.testInheritedClassMethod_py2
PASS: pytype.tests.test_methods.MethodsTest.testBooleanOp_py2
PASS: pytype.tests.test_methods.MethodsTest.testBooleanOp_py3
PASS: pytype.tests.test_methods.MethodsTest.testCallPositionalAsKeyword_py2
PASS: pytype.tests.test_methods.MethodsTest.testCallPositionalAsKeyword_py3
PASS: pytype.tests.test_methods.MethodsTest.testAmbiguousStarStar_py3
PASS: pytype.tests.test_methods.MethodsTest.testAmbiguousStarStar_py2
PASS: pytype.tests.test_methods.MethodsTest.testPositive_py3
PASS: pytype.tests.test_methods.MethodsTest.testPositive_py2
PASS: pytype.tests.test_methods.MethodsTest.testListGenerator_py2
PASS: pytype.tests.test_methods.MethodsTest.testListGenerator_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarStar2_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarStar2_py2
PASS: pytype.tests.test_methods.MethodsTest.testClassMethod_py2
PASS: pytype.tests.test_methods.MethodsTest.testClassMethod_py3
PASS: pytype.tests.test_methods.MethodsTest.testCallArgs_py3
PASS: pytype.tests.test_methods.MethodsTest.testCallArgs_py2
PASS: pytype.tests.test_methods.MethodsTest.testRegister_py3
PASS: pytype.tests.test_methods.MethodsTest.testRegister_py2
PASS: pytype.tests.test_methods.MethodsTest.testVariableProductComplexityLimit_py2
PASS: pytype.tests.test_methods.MethodsTest.testVariableProductComplexityLimit_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarStar_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarStar_py3
PASS: pytype.tests.test_methods.MethodsTest.testSlice_py3
PASS: pytype.tests.test_methods.MethodsTest.testSlice_py2
PASS: pytype.tests.test_methods.MethodsTest.testStaticMethod_py3
PASS: pytype.tests.test_methods.MethodsTest.testStaticMethod_py2
PASS: pytype.tests.test_methods.MethodsTest.testNegative_py3
PASS: pytype.tests.test_methods.MethodsTest.testNegative_py2
PASS: pytype.tests.test_methods.MethodsTest.testFuncName_py3
PASS: pytype.tests.test_methods.MethodsTest.testFuncName_py2
PASS: pytype.tests.test_methods.MethodsTest.testAttributeInNew_py3
PASS: pytype.tests.test_methods.MethodsTest.testAttributeInNew_py2
PASS: pytype.tests.test_methods.MethodsTest.testConjugate_py3
PASS: pytype.tests.test_methods.MethodsTest.testConjugate_py2
PASS: pytype.tests.test_methods.MethodsTest.testTwoClosures_py3
PASS: pytype.tests.test_methods.MethodsTest.testTwoClosures_py2
PASS: pytype.tests.test_methods.MethodsTest.testDeepClosure_py2
PASS: pytype.tests.test_methods.MethodsTest.testDeepClosure_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsPassThrough_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsPassThrough_py3
PASS: pytype.tests.test_methods.MethodsTest.testDecorator_py2
PASS: pytype.tests.test_methods.MethodsTest.testDecorator_py3
PASS: pytype.tests.test_methods.MethodsTest.testGenerators_py2
PASS: pytype.tests.test_methods.MethodsTest.testGenerators_py3
PASS: pytype.tests.test_methods.MethodsTest.testComplexCFG_py2
PASS: pytype.tests.test_methods.MethodsTest.testComplexCFG_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsType_py2
PASS: pytype.tests.test_methods.MethodsTest.testAddInt_py2
PASS: pytype.tests.test_methods.MethodsTest.testAddInt_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsDeep_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsDeep_py2
PASS: pytype.tests.test_methods.MethodsTest.testInheritNew_py3
PASS: pytype.tests.test_methods.MethodsTest.testInheritNew_py2
PASS: pytype.tests.test_methods.MethodsTest.testClosure_py2
PASS: pytype.tests.test_methods.MethodsTest.testClosure_py3
PASS: pytype.tests.test_methods.MethodsTest.testDefaultReturnType_py2
PASS: pytype.tests.test_methods.MethodsTest.testDefaultReturnType_py3
PASS: pytype.tests.test_methods.MethodsTest.testLookup_py2
PASS: pytype.tests.test_methods.MethodsTest.testLookup_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsType2_py2
PASS: pytype.tests.test_methods.MethodsTest.testStarArgsType2_py3
PASS: pytype.tests.test_methods.MethodsTest.testStarStarDeep2_py3
PASS: pytype.tests.test_methods.MethodsTest.testExplicitProperty_py3
PASS: pytype.tests.test_methods.MethodsTest.testExplicitProperty_py2
PASS: pytype.tests.test_methods.MethodsTest.testNot_py2
PASS: pytype.tests.test_methods.MethodsTest.testNot_py3
PASS: pytype.tests.test_methods.MethodsTest.testLoopsSanity_py2
PASS: pytype.tests.test_methods.MethodsTest.testLoopsSanity_py3
PASS: pytype.tests.test_methods.MethodsTest.testInvert_py2
PASS: pytype.tests.test_methods.MethodsTest.testInvert_py3
PASS: pytype.tests.test_methods.MethodsTest.testBuiltinStarArgs_py3
PASS: pytype.tests.test_methods.MethodsTest.testBuiltin
```

(That's not a mistake on my part, the log cuts off seemingly in the middle of a line)

**Comment by sivachandra** [comment]
Looking.

**Comment by sivachandra** [comment]
Are you able to repro this consistently? I have tried 20 times so far and it failed only twice. Both the times, when I executed the ninja command, the failure went away.

**Comment by rchen152** [comment]
Yes, I seem to be able to reproduce this consistently. My steps are:
```
git clone git@github.com:google/pytype.git --recurse-submodules
cd pytype/
git checkout -t origin/google_sync
git checkout c984ada
python build_scripts/run_tests.py
```
(My default Python is 2.7.)

**Comment by martindemello** [comment]
i ran that and the only failure was pytype.pytd.typeshed_test

$ cat
/usr/local/google/home/mdemello/tmp/pytype/out/pytype/pytd/typeshed_test.log

Running tests in module pytype.pytd.typeshed_test ...
Traceback (most recent call last):
  File
"/usr/local/google/home/mdemello/tmp/pytype/build_scripts/test_module.py",
line 211, in run_tests_in_module
    mod_object = __import__(options.fq_mod_name, fromlist=[fq_pkg_name])
  File
"/usr/local/google/home/mdemello/tmp/pytype/out/pytype/pytd/typeshed_test.py",
line 8, in <module>
    from pytype.tests import test_base
ImportError: cannot import name test_base

Ran 0 methods from 0 classes.
Found 0 errors
Found 0 failures
Found 0 unexpected successes

**Comment by sivachandra** [comment]
Is it the same test failing always?

If you are hitting it consistently, can you try something:

Over here, https://github.com/google/pytype/blob/google_sync/build_scripts/run_tests.py#L72,
instead of -k 100000, can you add -j 1 and see if you are able to reproduce. If yes, there are a few other things we can try starting from there.

**Comment by sivachandra** [comment]
You probably already know, "-j 1" means that we want to run only 1 job in parallel. So, it will take ~40 minutes to run the complete suite.

**Comment by sivachandra** [comment]
I made some progress with respect to what kind of problem it is: it is the flaky seg fault which shows up once in a while on TAP as well!

**Comment by rchen152** [comment]
!!! That's unexpected... But no, it's not always the same test, and that (sort of) explains why. I guess I'll push the typeshed_test change to this branch and try the tests again.

**Comment by sivachandra** [comment]
Ah sorry, I missed you second update.

**Comment by rchen152** [comment]
Looks like the typeshed test failure is present in all three versions now. I'll close this PR, delete the branch, then create a new one and open another PR.

**Pull request closed without merging**
