### PR TITLE
Fix for type coroutine

### PR DESCRIPTION
**Pull request by Arvind2222**
Coroutine type is "coroutine" which should be "Coroutine"
From the typing.Coroutine

### CODE REVIEW

**Comment by Arvind2222** [comment]
@googlebot I signed it!

**Comment by rchen152** [comment]
Could I ask what bug you're attempting to fix with this PR? Currently "coroutine" refers to builtins.coroutine (https://github.com/google/pytype/blob/3f46c16d16c1b597ffd9be69254a4d3004c10428/pytype/pytd/builtins/3/builtins.pytd#L827), and changing it to "Coroutine" causes test failures (https://travis-ci.org/github/google/pytype/jobs/668066986).

**Comment by Arvind2222** [comment]
@rchen152 The automated typing after running the merge-pyi gives a wrong type hint of coroutine instead of Coroutine.

**Comment by Arvind2222** [comment]
I checked the ci results. I think I made some wrong edit on my part. But the bug is still there. Ran on python 3.7.7.

**Comment by rchen152** [comment]
Thanks for the additional information! If it's possible for you to make a simple repro of the merge-pyi error, could you open a bug for it? I tried myself with:

```
async def f():
  pass
```

but the inferred return type was `typing.Coroutine`, not `builtins.coroutine`, and was correctly merged by merge-pyi.

**Pull request closed without merging**
