### PR TITLE
Report import errors due to bad deps.

### PR DESCRIPTION
**Pull request by rchen152**
PiperOrigin-RevId: 201481602

### CODE REVIEW

**Comment by rchen152** [comment]
Hey Siva, continuous-integration/travis-ci/pr failed with an error about cmake installation. Since this PR does include a change to test_module, I'm not sure if the failure is relevant or not. Could you take a look?

**Comment by sivachandra** [comment]
The failure is akin to a TAP tool failure. So, you should just click the "Restart Job" on the top right. I have done that now and it looks like order has been restored :)

**Comment by sivachandra** [comment]
If you did not already notice, the branch was green but the pull request went red.

**Comment by rchen152** [comment]
Ah, got it. Thanks!

**Pull request merged**
