### PR TITLE
Correct docstring about return value.

### PR DESCRIPTION
**Pull request by manueljacob**

### CODE REVIEW

**Comment by rchen152** [comment]
Thanks! Could you address the CLA check failure when you have a chance?

**Comment by manueljacob** [comment]
> Thanks! Could you address the CLA check failure when you have a chance?

I did that right after I got the notification. Did I miss anything?

**Comment by rchen152** [comment]
Ah you're right, looks like it's passing now. Sorry for the confusion!

**Review by rchen152 — APPROVED** [review]

**Comment by rchen152** [comment]
Thanks! Importing this PR requires a review from another pytype dev, so I'll do that in the morning.

**Comment by rchen152** [comment]
Merged as https://github.com/google/pytype/pull/1388/commits/42e805f3af4e599654c1113b82d4a4ea6a65eeab.

**Pull request closed without merging**
